### ISSUE TITLE
[Question] Is Tor proxy required?

### ISSUE THREAD

**Issue by DarkCat09** [TeamPiped/region-restriction-checker#84]
Hello.

What Tor proxy (in docker-compose) is used for?

And can I self-host the restriction checker without it to minimize CPU/RAM usage?

**Comment by FireMasterK** [comment]
Hi, the (rotating) Tor proxy used in `docker-compose.yml` is used to avoid being rate limited. Each request is made on a different IP.

You can use a different type of proxy if you would like to lower CPU and ram usage and accordingly configure the `PROXY` environment variable.

You could try [wireproxy](https://github.com/pufferffish/wireproxy) with [wgcf](https://github.com/ViRb3/wgcf) for example, but I'm not sure how reliable that would be at avoiding rate limits.

**Comment by DarkCat09** [comment]
Thanks a lot!

Didn't think that your tor-proxy image rotates IP on each request.  
OK, I'll check wgcf, but probably will use Tor.
